### ISSUE TITLE
fix repo description

### ISSUE THREAD

**Issue by jamesbeedy** [juju-solutions/layer-filebeat#30]
"Filebeat is part of the Elastic Beats suite, and allows you to ship files to logstash or kibana"

could be

"Filebeat is part of the Elastic Beats suite, and provides lightweight way to forward and centralize logs and files."

**Comment by kwmonroe** [comment]
I updated the repo desc to reflect the short filebeat description "Lightweight Shipper for Logs" from:

https://www.elastic.co/products/beats/filebeat

I also added that this is the repo for the filebeat **charm** source and set the website to the filebeat landing page in the charm store.
