### ISSUE TITLE
Fields config key not working as expected.

### ISSUE THREAD

**Issue by tasdomas** [juju-solutions/layer-filebeat#39]
From looking at the source of the charm, it looks like the `fields` config key is not handled as a space-separated list of items. Which results in an erroneous `/etc/filebeat/filebeat.yml` when using the config key with a value of e.g. `"type:syslog service:someservice"`

**Comment by axinojolais** [comment]
I think this can be resolved now, it certainly works fine for me

**Comment by kwmonroe** [comment]
Yeah, working for me as well.  Thx!
