### ISSUE TITLE
Sometimes kafka version needs to be set

### ISSUE THREAD

**Issue by tbaumann** [juju-solutions/layer-filebeat#54]
Newer kafka versions can have issues with older formats.
This config option is required https://www.elastic.co/guide/en/beats/filebeat/5.3/kafka-output.html#_version

I will add support for it...

**Comment by kwmonroe** [comment]
@tbaumann i see you've added a commit to include this support that lgtm.  If/when you're ready, submit a PR from your branch and I'll merge it in.

**Comment by tbaumann** [comment]
Will do tomorrow. Thanks

**Comment by tbaumann** [comment]
I had to rebase that commit a bit. But I got it cleaned up.

**Comment by kwmonroe** [comment]
Fixed by #57

**Comment by kwmonroe** [comment]
FYI, this has been released in charm rev >= 19:

https://jujucharms.com/filebeat/19
