### ISSUE TITLE
filebeat service needs to be restarted

### ISSUE THREAD

**Issue by marosg42** [juju-solutions/layer-filebeat#55]
After changing target kafka IPs, filebeat service is not restarted automatically.

**Comment by marosg42** [comment]
@kwmonroe 
kafka IP and topic were changed with juju config filebeat kafka_hosts...
I could see file filebeat.yml with new timestamp and new parameters
but when I checked filebeat process with ps, I could see it was still the old one, not restarted, also filebeat log showed no change
when I restarted it (service filebeat restart, it is on Ubuntu 14.04) I could see in filebeat log new values were picked up

Now when I think about it, this charm could be over a year old, I could check that. Could yoi point me to hook code where filebeat is actually restarted? I will check if that is present in that charm version

**Comment by kwmonroe** [comment]
@marosg42, the restart logic has changed quite a bit in the last few months -- here's where we currently check if the filebeat.yml has changed, and restart appropriately:

https://github.com/juju-solutions/layer-filebeat/blob/master/reactive/filebeat.py#L67

Configuring new kafka_hosts should definitely alter the filebeat.yaml and hence restart the service. 
 This would be included in revision 18 of filebeat in the charm store:

https://jujucharms.com/filebeat/

If your charm was deployed > 2 months ago, I would bet it doesn't have the most recent restart logic.

**Comment by marosg42** [comment]
@kwmonroe thank you, it was old charm version
