### ISSUE TITLE
status message shows incorrectly when manually configured logstash or kafka hosts are set

### ISSUE THREAD

**Issue by jamesbeedy** [juju-solutions/layer-filebeat#61]
filebeat charm status does not account for manually configure kafka or logstash hosts https://paste.ubuntu.com/p/TgWNKrs6rY/

**Comment by jamesbeedy** [comment]
fixed by https://github.com/juju-solutions/layer-filebeat/pull/60 and https://github.com/juju-solutions/layer-beats-base/pull/31

**Comment by tasdomas** [comment]
This still seems to be happening after charm update.

**Comment by kwmonroe** [comment]
Revision 20 contains the fixes noted by @jamesbeedy:

https://jujucharms.com/filebeat/20

It'll hang out in the edge channel pending tests, but I'll make a note here when it moves to stable.

**Comment by kwmonroe** [comment]
rev 20 has been in stable for a while now; closing out
