### ISSUE TITLE
Upgrade charm in Trusty environments fails

### ISSUE THREAD

**Issue by xavpaice** [juju-solutions/layer-filebeat#62]
When running a charm upgrade in an environment running Trusty, and Juju 1.25, during just about any hook, I get:

```
Traceback (most recent call last):
  File "./hooks/install", line 19, in <module>
    main()
  File "/var/lib/juju/agents/unit-filebeat-30/.venv/lib/python3.4/site-packages/charms/reactive/__init__.py", line 72, in main
    bus.dispatch(restricted=restricted_mode)
  File "/var/lib/juju/agents/unit-filebeat-30/.venv/lib/python3.4/site-packages/charms/reactive/bus.py", line 382, in dispatch
    _invoke(other_handlers)
  File "/var/lib/juju/agents/unit-filebeat-30/.venv/lib/python3.4/site-packages/charms/reactive/bus.py", line 358, in _invoke
    handler.invoke()
  File "/var/lib/juju/agents/unit-filebeat-30/.venv/lib/python3.4/site-packages/charms/reactive/bus.py", line 180, in invoke
    self._action(*args)
  File "/var/lib/juju/agents/unit-filebeat-30/charm/reactive/beats_base.py", line 15, in waiting_messaging
    status.waiting('Waiting for: elasticsearch, logstash or kafka.')
  File "lib/charms/layer/status.py", line 72, in waiting
    status_set(WorkloadState.WAITING, message)
  File "lib/charms/layer/status.py", line 100, in status_set
    layer = _find_calling_layer()
  File "lib/charms/layer/status.py", line 106, in _find_calling_layer
    fn = Path(frame.filename)
AttributeError: 'tuple' object has no attribute 'filename'
```

I tried rebuilding the charm locally and got a much newer charms.reactive (1.0.0), and that seems to work OK in this particular environment.  Any chance of a fresh build on the charmstore to catch that?

**Comment by kwmonroe** [comment]
@xavpaice the error you're getting stems from an incompatibility between python3.4 (which is what you get on trusty) and py3.5+.  It was reported here https://github.com/juju-solutions/layer-status/issues/1, but has been fixed for a while now.

Which charm revision were you running when you hit this?  The latest stable [filebeat-19](https://jujucharms.com/filebeat/) has this fix -- will that version work for you?

**Comment by xavpaice** [comment]
The charm version we were upgrading to was cs:filebeat-19, but yeah it's certainly Python 3.4.   I didn't take too close a look at what rebuilding actually collected on the way, but maybe -19 was just a touch earlier than the release of the fix?  I suspect the next release of the charm will collect the fix also and close this issue.

**Comment by kwmonroe** [comment]
@xavpaice filebeat-19 definitely contains the status fix -- you can see the workaround for python 3.4 in the `_find_calling_layer` function here:

https://api.jujucharms.com/charmstore/v5/filebeat-19/archive/lib/charms/layer/status.py

Contrast that with -18, which does *not* contain the fix:

https://api.jujucharms.com/charmstore/v5/filebeat-18/archive/lib/charms/layer/status.py

I tried reproducing your upgrade path by deploying an old revision; I used filebeat-15 just to pick something from well before the fix:
```bash
$ juju deploy ubuntu --series trusty
Located charm "cs:ubuntu-12".
Deploying charm "cs:ubuntu-12".

$ juju deploy filebeat-15 --series trusty
Located charm "cs:filebeat-15".
Deploying charm "cs:filebeat-15".

$ juju relate filebeat ubuntu

## wait a couple minutes

$ juju status
Model     Controller  Cloud/Region   Version  SLA          Timestamp
filebeat  aws-w       aws/us-west-1  2.4.0    unsupported  08:48:00-05:00

App       Version  Status   Scale  Charm     Store       Rev  OS      Notes
filebeat           waiting      1  filebeat  jujucharms   15  ubuntu
ubuntu    14.04    active       1  ubuntu    jujucharms   12  ubuntu

Unit           Workload  Agent  Machine  Public address  Ports  Message
ubuntu/0*      active    idle   0        52.53.224.137          ready
  filebeat/0*  waiting   idle            52.53.224.137          Waiting for connections.

Machine  State    DNS            Inst id              Series  AZ          Message
0        started  52.53.224.137  i-0b8ffa92de23fec32  trusty  us-west-1b  running
```

And then upgrading to -19 like this:
```bash
$ juju upgrade-charm filebeat
Added charm "cs:filebeat-19" to the model.

## wait a couple minutes

$ juju status
Model     Controller  Cloud/Region   Version  SLA          Timestamp
filebeat  aws-w       aws/us-west-1  2.4.0    unsupported  08:49:18-05:00

App       Version  Status   Scale  Charm     Store       Rev  OS      Notes
filebeat  5.6.12   waiting      1  filebeat  jujucharms   19  ubuntu
ubuntu    14.04    active       1  ubuntu    jujucharms   12  ubuntu

Unit           Workload  Agent  Machine  Public address  Ports  Message
ubuntu/0*      active    idle   0        52.53.224.137          ready
  filebeat/0*  waiting   idle            52.53.224.137          Waiting for: elasticsearch, logstash or kafka.

Machine  State    DNS            Inst id              Series  AZ          Message
0        started  52.53.224.137  i-0b8ffa92de23fec32  trusty  us-west-1b  running
```

As you can see by the filebeat status message, we did go through the code path that failed in your traceback:

https://github.com/juju-solutions/layer-beats-base/blob/master/reactive/beats_base.py#L15

But it was successful for me.  Is it possible you upgraded to filebeat-18 instead of -19?  As mentioned, -19 is the first revision to contain the fix.  If not, could you help me track this down with steps to reproduce?  Thanks!

**Comment by kwmonroe** [comment]
Closing out stale issues. Feel free to reopen if this issue is still valid.
