### ISSUE TITLE
Default logpath doesn't include syslog

### ISSUE THREAD

**Issue by xavpaice** [juju-solutions/layer-filebeat#64]
The default setting for logpath is "/var/log/*.log /var/log/*/*.log" which doesn't include /var/log/syslog.  Can we get that added to the default?

**Comment by kwmonroe** [comment]
I put this in by default for a short time, but the logging quickly got out of control. With the default `logging_to_syslog=True` config option, filebeat events are logged to `/var/log/syslog`.  Including that file in the list of log inputs causes a ton of events ("hey, i found something worth noting in syslog; oh hey, i'm watching syslog and something new came in; there's another one!", etc, etc).

We could mitigate this by configuring `exclude_lines` to skip syslog events generated by filebeat, but then you could miss filebeat events in other logs that you do care about.

I'm going to close this out for now, as I think there are enough config options exposed to achieve this without changing the current defaults.  Here are a couple examples:
```bash
## disable filebeat logging to syslog, start watching /var/log/syslog
juju config filebeat logging_to_syslog=False \
    logpath="/var/log/*.log /var/log/*/*.log /var/log/syslog"

## keep filebeat logging to syslog, watch /var/log/syslog excluding anything that starts with 'filebeat'
juju config filebeat logging_to_syslog=True \
    logpath="/var/log/*.log /var/log/*/*.log /var/log/syslog" \
    exclude_lines='["^filebeat"]'
