### ISSUE TITLE
post-system-upgrade hook fails with missing libs

### ISSUE THREAD

**Issue by xavpaice** [juju-solutions/layer-filebeat#65]
Upgrading from Trusty to Xenial (cs:filebeat-19):

2018-11-22 22:57:04 INFO juju.worker.uniter resolver.go:115 awaiting error resolution for "post-series-upgrade" hook
2018-11-22 22:57:04 DEBUG post-series-upgrade Could not find platform independent libraries <prefix>
2018-11-22 22:57:04 DEBUG post-series-upgrade Could not find platform dependent libraries <exec_prefix>
2018-11-22 22:57:04 DEBUG post-series-upgrade Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
2018-11-22 22:57:04 DEBUG post-series-upgrade Fatal Python error: Py_Initialize: Unable to get the locale encoding
2018-11-22 22:57:04 DEBUG post-series-upgrade ImportError: No module named 'encodings'
2018-11-22 22:57:05 ERROR juju.worker.uniter.operation runhook.go:132 hook "post-series-upgrade" failed: signal: aborted (core dumped)
2018-11-22 22:57:05 INFO juju.worker.uniter resolver.go:115 awaiting error resolution for "post-series-upgrade" hook

**Comment by xavpaice** [comment]
It looks like this is something broken in the venv:

```
root@grafana1:/var/lib/juju/agents/unit-filebeat-38# source .venv/bin/activate
(.venv)root@grafana1:/var/lib/juju/agents/unit-filebeat-38# python
Could not find platform independent libraries <prefix>
Could not find platform dependent libraries <exec_prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
Fatal Python error: Py_Initialize: Unable to get the locale encoding
ImportError: No module named 'encodings'
Aborted (core dumped)
```

**Comment by kwmonroe** [comment]
@xavpaice i'm guessing this has to do with the filebeat venv being created with trusty python (v3.4), and xenial python (v3.5) not liking it.

@johnsca, how can we rebuild charm venvs  after a series upgrade?  Could it be as simple as:
```bash
juju run --application filebeat 'rm $JUJU_CHARM_DIR/wheelhouse/.bootstrapped'
juju run --application filebeat 'hooks/update-status'
```

Maybe also need to `rm -rf $JUJU_CHARM_DIR/../.venv`.

**Comment by johnsca** [comment]
The venv should already be [cleared](https://github.com/juju-solutions/layer-basic/blob/master/lib/charms/layer/basic.py#L53-L56) and recreated by layer:basic so I'm not sure why it would still fail.  We might need better logging around that to ensure that it is doing that step, but my best guess at this point is that it may be a conflict between the [virtualenv package change between trusty & xenial](https://github.com/juju-solutions/layer-basic/blob/master/lib/charms/layer/basic.py#L87-L90).  It may be that an important part of manual upgrade process might be the need to remove `python-virtualenv` (since I'm not certain if we can do so after the series upgrade; if we can, then we should be able to automate it).

**Comment by kwmonroe** [comment]
@johnsca, i see that rev19 *does not* have the `layer-basic` change you noted. My new guess is that this will resolve itself with rev20, which has that change.

@xavpaice would it be possible for you to `juju upgrade-charm filebeat --channel candidate` to get the latest charm (https://jujucharms.com/filebeat/20)?

If the charm is still in a failed state, you may have to `juju resolved --no-retry filebeat/XX` a few times to get the actual `upgrade-charm` hook to run.

**Comment by xavpaice** [comment]
@kwmonroe I tried -20 on an environment that was about to get the upgrade, and that upgrades perfectly thanks!  The original env wasn't a candidate for that, I ended up removing filebeat entirely and starting fresh there.

Not sure if I should close now, or wait for -20 to get released.

**Comment by kwmonroe** [comment]
@xavpaice thanks a million for the verification.  rev 20 has been promoted to stable:

https://jujucharms.com/filebeat/

Closing this out, thanks again!
