### ISSUE TITLE
remove a relation should remove the host from logstash hosts

### ISSUE THREAD

**Issue by xavpaice** [juju-solutions/layer-filebeat#70]
We related filebeat to graylog, then added a new unit to graylog.  The new host was added in filebeat.yml as expected.  We then removed the 'old' graylog unit, and it's entry remained in the filebeat.yml but is no longer reachable.  Can we get the relation changed hooks to fix this?

**Comment by agileshaw** [comment]
This issue is resolved in layer-beats-base [PR#39](https://github.com/juju-solutions/layer-beats-base/pull/39)
