### ISSUE TITLE
Please consider allowing for user-defined extra inputs

### ISSUE THREAD

**Issue by Vultaire** [juju-solutions/layer-filebeat#76]
The problem I'm currently facing is a need to configure multiline settings for extracting messages from OpenStack logs and other log files and forwarding them to Graylog.  There may be a need to have different multiline patterns depending on the logs being processed.

Thus, I think an option should be added to layer-filebeat to allow specifying user-defined inputs via the charm's config.  This would allow the flexibility that is needed in this particular case, and does so with only minimal code changes.

I've provided a PR with a [rather trivial patch](https://github.com/juju-solutions/layer-filebeat/pull/75) which would enable this.  It's been tested specifically on the default 6.x series for filebeat; I have not yet tested 5.x/7.x.

**Comment by kwmonroe** [comment]
Fixed in #75.
