### ISSUE TITLE
wrong filebeat.registry.path causes a service failure to start

### ISSUE THREAD

**Issue by jpvs1978** [juju-solutions/layer-filebeat#85]
The default configuration provided by the charm is not working on the last versión of Filebeat
The registry file path is wrong, please see the documentation.
https://www.elastic.co/guide/en/beats/filebeat/current/configuration-general-options.html
filebeat.registry.path:

In the attached image please see the red arrow for bad config and green arrow for good config
![image](https://user-images.githubusercontent.com/18478358/118305674-47685700-b4b6-11eb-8d60-bdaaf44206a9.png)

The filebeat service failed to start and the log shows this:

May 14 17:17:19 blade04 filebeat[1403723]: Exiting: 1 error: setting 'filebeat.registry_file' has been removed

--------------------------------
May 14 17:17:19 blade04 filebeat[1403723]: INFO instance/beat.go:304 Setup Beat: filebeat; Version: 7.12.1
May 14 17:17:19 blade04 filebeat[1403723]: INFO [publisher] pipeline/module.go:113 Beat name: nova-compute/3
May 14 17:17:19 blade04 filebeat[1403723]: INFO instance/beat.go:437 filebeat stopped.
May 14 17:17:19 blade04 filebeat[1403723]: ERROR instance/beat.go:971 Exiting: 1 error: setting 'filebeat.registry_file' has been removed
May 14 17:17:19 blade04 filebeat[1403723]: Exiting: 1 error: setting 'filebeat.registry_file' has been removed
May 14 17:17:19 blade04 systemd[1]: filebeat.service: Main process exited, code=exited, status=1/FAILURE
May 14 17:17:19 blade04 systemd[1]: filebeat.service: Failed with result 'exit-code'.
May 14 17:17:19 blade04 systemd[1]: filebeat.service: Scheduled restart job, restart counter is at 5.
May 14 17:17:19 blade04 systemd[1]: Stopped Filebeat sends log files to Logstash or directly to Elasticsearch..
May 14 17:17:19 blade04 systemd[1]: filebeat.service: Start request repeated too quickly.
May 14 17:17:19 blade04 systemd[1]: filebeat.service: Failed with result 'exit-code'.
May 14 17:17:19 blade04 systemd[1]: Failed to start Filebeat sends log files to Logstash or directly to Elasticsearch..
------------------------------------

**Comment by agileshaw** [comment]
filebeat registry directory path was removed from `filebeat-7.yaml`in #92 because there's no config option to change this path. The default path used is`${path.data}/registry` ([ref]).

[ref]: https://www.elastic.co/guide/en/beats/filebeat/current/configuration-general-options.html#_registry_path
